title: RSE pioneers
description: >- # this means to ignore newlines until "baseurl:"
  The website hosting the RSE pioneers project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  iulusoy

# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-sitemap

# Minimal Mistakes theme settings
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Custom theme colors
sass:
  sass_dir: _sass
  style: compressed

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/iulusoy/RSE-pioneers"
    - label: "Podcast"
      icon: "fas fa-fw fa-podcast"
      url: "https://www.buzzsprout.com/2531619"

# Site Author
author:
  name: "RSE Pioneers"
  avatar: "/assets/images/RSE-pioneer.png"
  bio: "Documenting the contributions of research software engineering pioneers."
  location: "Heidelberg, Germany"
  email: 
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/iulusoy"
    - label: "Buzzsprout Podcast"
      icon: "fas fa-fw fa-podcast"
      url: "https://www.buzzsprout.com/2531619"

# Reading Files
include:
  - .htaccess
  - _pages
  - 01-Dieter-Meyer

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

